### ISSUE TITLE
apply-manifest SysSetting returns error when called without -e

### ISSUE THREAD

**Issue by kirillkrylov** [Advance-Technologies-Foundation/clio#285]
![image](https://github.com/Advance-Technologies-Foundation/clio/assets/7285114/30575dc7-60e0-439b-9e5e-1d2d53c7fa0c)

```yaml
environment:
  url: "http://kkrylovn.tscrm.com:40060"
  login: Supervisor
  password: Supervisor
  platformversion: "8.1.3"
  platformtype: "NETFramework"


settings:
  - code: "MrktApolloApiKey"
    value: "My-Key-should-be-here"


app_hubs:
  - name: CreatioComposableApps
    path: "//tscrm.com/dfs-ts/ComposableApps"
  - name: MyLocalAppHub
    path: "C:/AppHub"

```
